#!/usr/bin/env python
#
# Copyright 2011 Splunk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"): you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""Helper script for running Java SDK examples."""

from subprocess import Popen
import sys

if len(sys.argv) == 1: sys.exit(0)
cmdline = "java -jar dist/examples/%s.jar" % sys.argv[1]
cmdline = cmdline.split()
cmdline.extend(sys.argv[2:])
process = Popen(cmdline, env={})
process.communicate()
sys.exit(process.wait())
