#!/bin/sh

#
# Shell script to build SDK jar and launch named sample.
#
#   Usage: run {sample}
#
# Example: ./run spurl --host=localhost /services/search/jobs
#

echo Building ..
ant -q -logfile build.log
if [ $? -ne 0 ] ; then
    cat build.log
    exit $?
fi
echo Running $1.jar ..
java -jar dist/examples/$1.jar $2 $3 $4 $5 $6 $7 $8 $9
