package com.splunk.erp.commons;

public enum HEADER_FIELDS{
	
	HOST("fields.host"),TRUNCATE("props.TRUNCATE"),INDEX("fields.index"),SOURCE("fields.source"),SOURCETYPE("fields.sourcetype"),KV_MODE("props.KV_MODE"),
	LINE_BREAKER("props.LINE_BREAKER"),SHOULD_LINEMERGE("props.SHOULD_LINEMERGE"),BREAK_ONLY_BEFORE_DATE("props.BREAK_ONLY_BEFORE_DATE"),
	CHARSET("props.CHARSET"), LINE_BREAKER_LOOKBEHIND("props.LINE_BREAKER_LOOKBEHIND"),BREAK_ONLY_BEFORE("props.BREAK_ONLY_BEFORE"),
	MUST_BREAK_AFTER("props.MUST_BREAK_AFTER"),MUST_NOT_BREAK_AFTER("props.MUST_NOT_BREAK_AFTER"),MUST_NOT_BREAK_BEFORE("props.MUST_NOT_BREAK_BEFORE"),
	MAX_EVENTS("props.MAX_EVENTS"),DATETIME_CONFIG("props.DATETIME_CONFIG"),TIME_PREFIX("props.TIME_PREFIX"),MAX_TIMESTAMP_LOOKAHEAD("props.MAX_TIMESTAMP_LOOKAHEAD"),
	TIME_FORMAT("props.TIME_FORMAT"), TZ("props.TZ"), TZ_ALIAS("props.TZ_ALIAS"), MAX_DAYS_AGO("props.MAX_DAYS_AGO"), MAX_DAYS_HENCE("props.MAX_DAYS_HENCE"),
	MAX_DIFF_SECS_AGO("props.MAX_DIFF_SECS_AGO"),MAX_DIFF_SECS_HENCE("props.MAX_DIFF_SECS_HENCE"),TIMESTAMP_FIELDS("props.TIMESTAMP_FIELDS"),FIELD_DELIMITER("props.FIELD_DELIMITER"),
	HEADER_FILE_DELIMITER("props.HEADER_FILE_DELIMITER"),FIELD_QUOTE("props.FIELD_QUOTE"), FIELD_NAMES("props.FIELD_NAMES"),MISSING_VALUE_REGEX("props.MISSING_VALUE_REGEX");
	
	private String field;
	
	private HEADER_FIELDS(String field)
	{
		this.field = field;
	}
	
	public String getFieldName(){
		return field;
	}
}
