/*
 * Copyright 2014 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package com.splunk;

import java.util.ArrayList;
import java.util.Collection;

/**
 * Abstract class specifying a calculation on a data model object.
 */
public abstract class Calculation {
    private final DataModelObject owner;
    private final String calculationID;
    private final Collection<Field> generatedFields;
    private final String comment;

    public Calculation(DataModelObject owner, String calculationID, Collection<Field> generatedFields, String comment) {
        this.owner = owner;
        this.calculationID = calculationID;
        this.generatedFields = generatedFields;
        this.comment = comment;
    }

    /**
     * @return the ID of this calculation.
     */
    public String getCalculationID() { return this.calculationID; }

    /**
     * @return a collection of the names of fields generated by this calculation.
     */
    public Collection<String> getGeneratedFieldNames() {
        ArrayList<String> result = new ArrayList<String>();
        for (Field f : generatedFields) {
            result.add(f.getName());
        }
        return result;
    }

    /**
     * @return a collection of the fields this calculation generates.
     */
    public Collection<Field> getGeneratedFields() { return this.generatedFields; }

    /**
     * @return the comment on this calculation (if one is specified) or null.
     */
    public String getComment() { return this.comment; }
}
