package com.splunk;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

public class DataModelObject {
    private String comment;
    private DataModel model;
    private String name;
    private String[] lineage;
    private String displayName;
    private String parentName;
    private Collection<String> children;

    private Map<String, Field> fields;
    private Collection<Constraint> constraints;
    private Map<String, Calculation> calculations;

    private DataModelObject(DataModel model) {
        this.model = model;
        this.fields = new HashMap<String, Field>();
        this.children = new ArrayList<String>();
        this.constraints = new ArrayList<Constraint>();
        this.calculations = new HashMap<String, Calculation>();
    }

    /**
     * Checks whether there is a field with the given name in this
     * data model object.
     *
     * @param fieldName name of the field to check for.
     * @return true if there is such a field; false otherwise.
     */
    public boolean containsField(String fieldName) {
        return fields.containsKey(fieldName);
    }

    /**
     * Local acceleration is tsidx acceleration of a data model object that is handled
     * manually by a user. You create a job which generates an index, and then use that
     * index in your pivots on the data model object.
     *
     * The namespace to this job is where the tsidx index will be stored. It should be
     * unique, or multiple jobs may clobber each other.
     *
     * When you have created a job using this method, then you can generate an accelerated
     * pivot by passing the same namespace to the pivot method.
     *
     * It is the user's responsibility to manage this job, including cancelling it.
     *
     * @param namespace The tsidx namespace to create.
     * @return a Job writing a tsidx index.
     */
    public Job createLocalAccelerationJob(String namespace) {
        return createLocalAccelerationJob(namespace, null);
    }

    /**
     * Local acceleration is tsidx acceleration of a data model object that is handled
     * manually by a user. You create a job which generates an index, and then use that
     * index in your pivots on the data model object.
     *
     * The namespace to this job is where the tsidx index will be stored. It should be
     * unique, or multiple jobs may clobber each other.
     *
     * When you have created a job using this method, then you can generate an accelerated
     * pivot by passing the same namespace to the pivot method.
     *
     * It is the user's responsibility to manage this job, including cancelling it.
     *
     * @param namespace The tsidx namespace to create.
     * @param earliestTime A time modifier (e.g., "-2w") setting the earliest time to index.
     * @return a Job writing a tsidx index.
     */
    public Job createLocalAccelerationJob(String namespace, String earliestTime) {
        String query = "| datamodel " + this.model.getName() + " " +
                this.getName() + " search | tscollect namespace=" + namespace;
        JobArgs args = new JobArgs();
        if (earliestTime != null) {
            args.setEarliestTime(earliestTime);
        }
        return this.model.getService().getJobs().create(query, args);
    }

    /**
     * Get the tsidx namespace that this object's containing data model uses for
     * global acceleration. Even if there is no acceleration on the model, this method
     * will still return a tsidx namespace.
     *
     * @return the global acceleration namespace of the data model containing this object.
     */
    public String getAccelerationNamespace() {
        return getDataModel().getAccelerationNamespace();
    }

    /**
     * Return a Splunk query that will produce the events in this data model object, using
     * global acceleration if possible.
     *
     * @return a String containing a search query.
     */
    public String getAcceleratedQuery() {
        if (this.getDataModel().isAccelerated()) {
            return "| tstats namspace=" + this.getAccelerationNamespace();
        } else {
            return "| datamodel " + this.model.getName() + " " + this.getName() + " search";
        }
    }

    /**
     * Return a Splunk query that will produce events in this data model from the specified
     * tsidx namespace (which is assumed to be generated by a job created by the
     * createLocalAccelerationJob method).
     *
     * @param namespace The tsidx namespace to generate a query on.
     * @return A String containing a search query.
     */
    public String getAcceleratedQuery(String namespace) {
        return "| tstats namespace=" + namespace;
    }

    public Map<String, Calculation> getCalculations() {
        return this.calculations;
    }

    public Calculation getCalcualtion(String calculationId) {
        return this.calculations.get(calculationId);
    }

    public Collection<DataModelObject> getChildren() {
        Collection<DataModelObject> children = new ArrayList<DataModelObject>();

        DataModel model = this.getDataModel();
        for (String childName : getChildrenNames()) {
            children.add(model.getObject(childName));
        }

        return children;
    }

    /**
     * @return a collection of string giving the names of all children of this object in the data model.
     */
    public Collection<String> getChildrenNames() {
        return children;
    }

    /**
     * @return a human readable comment on this object.
     */
    public String getComment() {
        return this.comment;
    }

    public Collection<Constraint> getConstraints() {
        return this.constraints;
    }

    /**
     * Fetch the data model on which this object is defined.
     *
     * @return A DataModel instance containing this object.
     */
    public DataModel getDataModel() {
        return this.model;
    }

    /**
     * @return the human readable name of this data model object.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Fetch a single field of a given name from this data model object.
     *
     * @param fieldName Name of the field to fetch.
     * @return A Field object, or null if there is no field of the given name.
     */
    public Field getField(String fieldName) {
        return fields.get(fieldName);
    }

    /**
     * Get a collection of objects specifying all the fields that defined on events
     * produced by this data model object.
     *
     * @return a collection of Field objects.
     */
    public Collection<Field> getFields() {
        return fields.values();
    }

    public String getQuery() {
        return "| datamodel " + this.model.getName() + " " + this.getName() + " search";
    }

    /**
     * @return Splunk's identifier for this data model object.
     */
    public String getName() { return this.name; }

    /**
     * Data model objects can inherit from other data model objects
     * in the same data model (or from a couple of global base objects
     * such as BaseEvent and BaseTransaction). The lineage is a list of
     * data model object names tracing this inheritance, starting with the
     * most remote ancestor and ending with this object.
     *
     * @return An array of names, starting with this object's name, followed by
     * the names up the hierarchy.
     */
    public String[] getLineage() { return this.lineage; }

    /**
     * Returns the name of the parent of this object.
     *
     * @return a String giving the name.
     */
    public String getParentName() {
        return this.parentName;
    }

    public Job runQuery() {
        return runQuery("", null);
    }

    public Job runQuery(JobArgs args) {
        return runQuery("", args);
    }

    public Job runQuery(String querySuffix) {
        return runQuery(querySuffix, null);
    }

    public Job runQuery(String querySuffix, JobArgs args) {
        return getDataModel().getService().getJobs().create(getAcceleratedQuery() + querySuffix, args);
    }

    public Pivot pivot(PivotArgs pivotArgs) {
        // TODO implement me
        return null;
    }

    public static DataModelObject parse(DataModel dataModel, JsonElement object) {
        DataModelObject dmo = new DataModelObject(dataModel);

        for (Entry<String, JsonElement> entry : object.getAsJsonObject().entrySet()) {
            if (entry.getKey().equals("objectName")) {
                dmo.name = entry.getValue().getAsString();
            } else if (entry.getKey().equals("displayName")) {
                dmo.displayName = entry.getValue().getAsString();
            } else if (entry.getKey().equals("comment")) {
                dmo.comment = entry.getValue().getAsString();
            } else if (entry.getKey().equals("lineage")) {
                dmo.lineage = entry.getValue().getAsString().split("\\.");
            } else if (entry.getKey().equals("displayName")) {
                dmo.displayName = entry.getValue().getAsString();
            } else if (entry.getKey().equals("parentName")) {
                dmo.parentName = entry.getValue().getAsString();
            } else if (entry.getKey().equals("fields")) {
                JsonArray fieldsJson = entry.getValue().getAsJsonArray();
                dmo.fields.clear();

                for (JsonElement fieldJson : fieldsJson) {
                    Field field = Field.parse(fieldJson);
                    dmo.fields.put(field.getName(), field);
                }
            } else if (entry.getKey().equals("children")) {
                JsonArray childrenJson = entry.getValue().getAsJsonArray();

                for (JsonElement childJson : childrenJson) {
                    dmo.children.add(childJson.getAsString());
                }

            } else if (entry.getKey().equals("constraints")) {
                JsonArray constraintsJson = entry.getValue().getAsJsonArray();

                for (JsonElement constraintJson : constraintsJson) {
                    Constraint constraint = Constraint.parse(constraintJson);
                    dmo.constraints.add(constraint);
                }
            } else if (entry.getKey().equals("calculations")) {
                for (JsonElement cjson : entry.getValue().getAsJsonArray()) {
                    Calculation c = Calculation.parse(cjson);
                    String cid = c.getCalculationID();
                    dmo.calculations.put(cid, c);
                }
            }
        }

        return dmo;
    }
}
